# Generated by Django 3.0.8 on 2020-07-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'casa',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Casa')),
            ],
            options={
                'db_table': 'comodo',
            },
        ),
        migrations.CreateModel(
            name='ComodoSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comodo')),
            ],
            options={
                'db_table': 'comodo_saida',
            },
        ),
        migrations.CreateModel(
            name='ConsumoHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
                ('comodo_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ComodoSaida')),
            ],
            options={
                'db_table': 'consumo_hora',
            },
        ),
        migrations.CreateModel(
            name='ConsumoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Casa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
            ],
            options={
                'db_table': 'consumo_mes',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo')),
            ],
            options={
                'db_table': 'saida',
            },
        ),
        migrations.CreateModel(
            name='MesHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConsumoHora')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConsumoMes')),
            ],
            options={
                'db_table': 'mes_hora',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('consumo_agua', models.FloatField()),
                ('consumo_energia', models.FloatField()),
                ('essencial', models.BooleanField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo')),
            ],
            options={
                'db_table': 'equipamento',
            },
        ),
        migrations.AddField(
            model_name='comodosaida',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipamento'),
        ),
        migrations.AddField(
            model_name='comodosaida',
            name='saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Saida'),
        ),
    ]
