# Generated by Django 3.1 on 2020-09-19 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'casa',
            },
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.IntegerField()),
                ('temperatura', models.IntegerField(default=0)),
                ('umidade', models.IntegerField(default=0)),
                ('vento', models.IntegerField(default=0)),
                ('pressao', models.IntegerField(default=0)),
                ('chuva', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'clima',
            },
        ),
        migrations.CreateModel(
            name='Coeficiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisao', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('feriado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'coeficientes',
            },
        ),
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('meta_agua_semana', models.IntegerField(default=0)),
                ('meta_agua_feriado', models.IntegerField(default=0)),
                ('meta_energia_semana', models.IntegerField(default=0)),
                ('meta_energia_feriado', models.IntegerField(default=0)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casa')),
            ],
            options={
                'db_table': 'comodo',
            },
        ),
        migrations.CreateModel(
            name='ComodoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.IntegerField()),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodo')),
            ],
            options={
                'db_table': 'comodo_equipamento',
            },
        ),
        migrations.CreateModel(
            name='ComodoSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.IntegerField()),
                ('essencial', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('tempo_min_semana', models.IntegerField(null=True)),
                ('tempo_max_semana', models.IntegerField(null=True)),
                ('tempo_min_feriado', models.IntegerField(null=True)),
                ('tempo_max_feriado', models.IntegerField(null=True)),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodo')),
                ('comodo_equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comodoequipamento')),
            ],
            options={
                'db_table': 'comodo_saida',
            },
        ),
        migrations.CreateModel(
            name='TipoConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_consumo',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_equipamento',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tipo_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoconsumo')),
            ],
            options={
                'db_table': 'saida',
            },
        ),
        migrations.CreateModel(
            name='GrupoCoeficientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisao', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('meta_agua_semana', models.IntegerField(default=0)),
                ('meta_agua_feriado', models.IntegerField(default=0)),
                ('meta_energia_semana', models.IntegerField(default=0)),
                ('meta_energia_feriado', models.IntegerField(default=0)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casa')),
            ],
            options={
                'db_table': 'grupo_coeficientes',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('consumo_agua', models.FloatField()),
                ('consumo_energia', models.FloatField()),
                ('tipo_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoconsumo')),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoequipamento')),
            ],
            options={
                'db_table': 'equipamento',
            },
        ),
        migrations.CreateModel(
            name='ConsumoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('agua', models.IntegerField(default=0)),
                ('agua_semana', models.IntegerField(default=0)),
                ('agua_feriado', models.IntegerField(default=0)),
                ('energia', models.IntegerField(default=0)),
                ('energia_semana', models.IntegerField(default=0)),
                ('energia_feriado', models.IntegerField(default=0)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casa')),
            ],
            options={
                'db_table': 'consumo_mes',
            },
        ),
        migrations.CreateModel(
            name='ConsumoHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.IntegerField()),
                ('data', models.DateField()),
                ('hora', models.IntegerField()),
                ('comodo_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodosaida')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumomes')),
            ],
            options={
                'db_table': 'consumo_hora',
            },
        ),
        migrations.AddField(
            model_name='comodosaida',
            name='saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.saida'),
        ),
        migrations.AddField(
            model_name='comodoequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
        ),
        migrations.CreateModel(
            name='CoeficienteValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=22, max_digits=24)),
                ('coeficiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coeficiente')),
            ],
            options={
                'db_table': 'coeficiente_valor',
            },
        ),
        migrations.AddField(
            model_name='coeficiente',
            name='comodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodo'),
        ),
        migrations.AddField(
            model_name='coeficiente',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupocoeficientes'),
        ),
    ]
