# Generated by Django 3.1 on 2020-09-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodo',
            name='meta_agua_feriado',
        ),
        migrations.RemoveField(
            model_name='comodo',
            name='meta_agua_semana',
        ),
        migrations.RemoveField(
            model_name='comodo',
            name='meta_energia_feriado',
        ),
        migrations.RemoveField(
            model_name='comodo',
            name='meta_energia_semana',
        ),
        migrations.RemoveField(
            model_name='grupocoeficientes',
            name='meta_agua_feriado',
        ),
        migrations.RemoveField(
            model_name='grupocoeficientes',
            name='meta_agua_semana',
        ),
        migrations.RemoveField(
            model_name='grupocoeficientes',
            name='meta_energia_feriado',
        ),
        migrations.RemoveField(
            model_name='grupocoeficientes',
            name='meta_energia_semana',
        ),
        migrations.AddField(
            model_name='consumomes',
            name='reduzir_agua_feriado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='reduzir_agua_semana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='reduzir_energia_feriado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='reduzir_energia_semana',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ComodoValorY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.IntegerField()),
                ('meta_agua', models.IntegerField(default=0)),
                ('meta_energia', models.IntegerField(default=0)),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodo')),
            ],
            options={
                'db_table': 'comodo_valor_y',
            },
        ),
    ]
