# Generated by Django 3.0.8 on 2020-08-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='descricao',
            field=models.CharField(default='Equipamento feito no banco 0001', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
