# Generated by Django 3.1 on 2020-09-15 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodocategoria',
            name='mes',
        ),
        migrations.AddField(
            model_name='comodocategoria',
            name='dia_mes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.diames'),
            preserve_default=False,
        ),
    ]
