# Generated by Django 3.1 on 2020-09-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumohora',
            name='categoria',
        ),
        migrations.CreateModel(
            name='ComodoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodo')),
            ],
            options={
                'db_table': 'comodo_categoria',
            },
        ),
    ]
