# Generated by Django 3.1 on 2020-09-15 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200913_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='comodocategoria',
            name='mes',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, to='core.consumomes'),
            preserve_default=False,
        ),
    ]
