# Generated by Django 3.0.8 on 2020-08-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200802_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
