# Generated by Django 3.1 on 2020-09-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200915_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumomes',
            name='temperatura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='umidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='vento',
            field=models.IntegerField(default=0),
        ),
    ]
