# Generated by Django 3.1 on 2020-09-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200915_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coeficientevalor',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='comodocategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='consumomes',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
