# Generated by Django 3.1 on 2020-09-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200920_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCoeficiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisao', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('reduzir_agua_semana', models.IntegerField(default=0)),
                ('reduzir_agua_feriado', models.IntegerField(default=0)),
                ('reduzir_energia_semana', models.IntegerField(default=0)),
                ('reduzir_energia_feriado', models.IntegerField(default=0)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casa')),
            ],
            options={
                'db_table': 'grupo_coeficientes',
            },
        ),
        migrations.CreateModel(
            name='Coeficiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisao', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('temperatura', models.IntegerField(default=0)),
                ('umidade', models.IntegerField(default=0)),
                ('vento', models.IntegerField(default=0)),
                ('pressao', models.IntegerField(default=0)),
                ('chuva', models.IntegerField(default=0)),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupocoeficiente')),
            ],
            options={
                'db_table': 'coeficientes',
            },
        ),
    ]
