# Generated by Django 3.0.8 on 2020-08-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200802_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tempo_uso_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tempo_uso_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
