# Generated by Django 3.1 on 2020-09-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coeficiente_grupocoeficiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='coeficiente',
            name='constante',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coeficiente',
            name='energia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coeficiente',
            name='semana',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coeficiente',
            name='chuva',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coeficiente',
            name='pressao',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coeficiente',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coeficiente',
            name='umidade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coeficiente',
            name='vento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grupocoeficiente',
            name='reduzir_agua_feriado',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grupocoeficiente',
            name='reduzir_agua_semana',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grupocoeficiente',
            name='reduzir_energia_feriado',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grupocoeficiente',
            name='reduzir_energia_semana',
            field=models.FloatField(default=0),
        ),
    ]
