# Generated by Django 3.1 on 2020-09-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200916_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodocategoria',
            name='data',
        ),
        migrations.RemoveField(
            model_name='comodocategoria',
            name='hora',
        ),
        migrations.AddField(
            model_name='comodocategoria',
            name='meta_agua',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comodocategoria',
            name='meta_energia',
            field=models.IntegerField(default=0),
        ),
    ]
