# Generated by Django 3.0.8 on 2020-08-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200804_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='tempo_uso_max',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tempo_uso_min',
        ),
        migrations.AddField(
            model_name='comodosaida',
            name='tempo_max_feriado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comodosaida',
            name='tempo_max_semana',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comodosaida',
            name='tempo_min_feriado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comodosaida',
            name='tempo_min_semana',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
