# Generated by Django 3.1 on 2020-09-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200917_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.IntegerField()),
                ('temperatura', models.IntegerField(default=0)),
                ('umidade', models.IntegerField(default=0)),
                ('vento', models.IntegerField(default=0)),
                ('pressao', models.IntegerField(default=0)),
                ('chuva', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'clima',
            },
        ),
        migrations.RenameField(
            model_name='comodocategoria',
            old_name='meta_agua',
            new_name='meta_agua_feriado',
        ),
        migrations.RenameField(
            model_name='comodocategoria',
            old_name='meta_energia',
            new_name='meta_agua_semana',
        ),
        migrations.RemoveField(
            model_name='consumomes',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='consumomes',
            name='umidade',
        ),
        migrations.RemoveField(
            model_name='consumomes',
            name='vento',
        ),
        migrations.RemoveField(
            model_name='diames',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='diames',
            name='umidade',
        ),
        migrations.RemoveField(
            model_name='diames',
            name='vento',
        ),
        migrations.AddField(
            model_name='comodocategoria',
            name='meta_energia_feriado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comodocategoria',
            name='meta_energia_semana',
            field=models.IntegerField(default=0),
        ),
    ]
