# Generated by Django 3.1 on 2020-09-29 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200921_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocoeficiente',
            name='mes',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConsumoHoraManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_liga', models.TimeField()),
                ('hora_desliga', models.TimeField()),
                ('semana', models.BooleanField(default=True)),
                ('comodo_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodosaida')),
            ],
            options={
                'db_table': 'consumo_hora_manual',
            },
        ),
    ]
