# Generated by Django 3.1 on 2020-09-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200928_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupocoeficiente',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='grupocoeficiente',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='grupocoeficiente',
            name='reduzir_agua_feriado',
        ),
        migrations.RemoveField(
            model_name='grupocoeficiente',
            name='reduzir_agua_semana',
        ),
        migrations.RemoveField(
            model_name='grupocoeficiente',
            name='reduzir_energia_feriado',
        ),
        migrations.RemoveField(
            model_name='grupocoeficiente',
            name='reduzir_energia_semana',
        ),
        migrations.CreateModel(
            name='MetaTreino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=30)),
                ('reduzir_agua_semana', models.FloatField(default=0)),
                ('reduzir_agua_feriado', models.FloatField(default=0)),
                ('reduzir_energia_semana', models.FloatField(default=0)),
                ('reduzir_energia_feriado', models.FloatField(default=0)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casa')),
            ],
            options={
                'db_table': 'meta_treino',
            },
        ),
        migrations.AddField(
            model_name='grupocoeficiente',
            name='meta_treino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.metatreino'),
            preserve_default=False,
        ),
    ]
