# Generated by Django 3.0.8 on 2020-08-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200804_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='tipo_equipamnto',
            new_name='tipo_equipamento',
        ),
    ]
