# Generated by Django 3.0.8 on 2020-08-11 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200804_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comodosaida',
            name='equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Equipamento'),
        ),
    ]
