# Generated by Django 3.1 on 2020-10-01 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grupocoeficiente_tempo_treino'),
    ]

    operations = [
        migrations.AddField(
            model_name='comodovalory',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.metatreino'),
            preserve_default=False,
        ),
    ]
