# Generated by Django 3.0.8 on 2020-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200814_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comodosaida',
            name='Apelido',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
