# Generated by Django 3.0.8 on 2020-08-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comodosaida_apelido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comodosaida',
            old_name='Apelido',
            new_name='apelido',
        ),
    ]
