# Generated by Django 3.0.8 on 2020-08-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200814_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumohora',
            name='mes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ConsumoMes'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MesHora',
        ),
    ]
