# Generated by Django 3.0.8 on 2020-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200822_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumomes',
            name='mes',
            field=models.CharField(max_length=30),
        ),
    ]
