# Generated by Django 3.0.8 on 2020-08-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200823_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumomes',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
        ),
    ]
