# Generated by Django 3.0.8 on 2020-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200823_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumomes',
            name='ano',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
