# Generated by Django 3.0.8 on 2020-08-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_consumomes_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumohora',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
        ),
    ]
