# Generated by Django 3.0.8 on 2020-08-26 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200823_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coeficiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisao', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comodo')),
            ],
            options={
                'db_table': 'coeficientes',
            },
        ),
        migrations.AddField(
            model_name='consumomes',
            name='agua',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='energia',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CoeficienteValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=22, max_digits=24)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoEquipamento')),
                ('coeficiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coeficiente')),
            ],
        ),
    ]
