# Generated by Django 3.1 on 2020-08-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200825_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupocoeficientes',
            name='status',
        ),
        migrations.AddField(
            model_name='grupocoeficientes',
            name='meta_agua',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupocoeficientes',
            name='meta_energia',
            field=models.IntegerField(default=0),
        ),
    ]
