# Generated by Django 3.0.8 on 2020-08-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200828_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupocoeficientes',
            old_name='meta_agua',
            new_name='meta_agua_feriado',
        ),
        migrations.RenameField(
            model_name='grupocoeficientes',
            old_name='meta_energia',
            new_name='meta_agua_semana',
        ),
        migrations.AddField(
            model_name='coeficiente',
            name='feriado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='agua_feriado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='agua_semana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='energia_feriado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumomes',
            name='energia_semana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupocoeficientes',
            name='meta_energia_feriado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupocoeficientes',
            name='meta_energia_semana',
            field=models.IntegerField(default=0),
        ),
    ]
